global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds.
  evaluation_interval: 30s # Evaluate rules every 30 seconds.
  external_labels:
    service_owner: ${SERVICE_OWNER} # replace this with your Operator name you want to be identified by, it helps us route alerts and metrics to your notification channels easily

remote_write:
  - url: https://vm.monitoring.gcp.obol.tech/write
    authorization:
      credentials: $PROM_REMOTE_WRITE_TOKEN
    write_relabel_configs:
      - source_labels: [job]
        regex: "charon"
        action: keep # Keeps charon metrics and drop metrics from other containers.

scrape_configs:
  - job_name: "execution-client"
    static_configs:
      - targets: ["execution-client:6060"]
  - job_name: "consensus-client"
    static_configs:
      - targets: ["consensus-client:5054"]
  - job_name: "charon"
    static_configs:
      - targets: ["dvt-client:3620"]
  - job_name: "validator-client"
    static_configs:
      - targets: ["validator-client:5064"]
  - job_name: "validator-ejector"
    static_configs:
      - targets: ["validator-ejector:8989"]
